export type PluginCatalogEntry = {
  id: string;
  name: string;
  description: string;
  category: string;
};

export type McpServerCatalogEntry = {
  id: string;
  name: string;
  description: string;
};

export type AgentCatalogEntry = {
  id: string;
  name: string;
  description: string;
};

export const DEFAULT_PLUGIN_CATALOG: PluginCatalogEntry[] = [
  { id: "hugging-face", name: "Hugging Face", description: "Inspect models, datasets, Spaces, and research", category: "Coding" },
  { id: "netlify", name: "Netlify", description: "Deploy projects and manage releases", category: "Coding" },
  { id: "vercel", name: "Vercel", description: "Build and deploy web apps and agents", category: "Coding" },
  { id: "game-studio", name: "Game Studio", description: "Design, prototype, and ship browser games", category: "Coding" },
  { id: "superpowers", name: "Superpowers", description: "Planning, TDD, debugging, and delivery workflows for coding agents", category: "Coding" },
  { id: "github", name: "GitHub", description: "Triage PRs, issues, CI, and publish flows", category: "Coding" },
  { id: "circleci", name: "CircleCI", description: "Build, test, and deploy any application", category: "Coding" },
  { id: "cloudflare", name: "Cloudflare", description: "Cloudflare platform guidance with official MCP", category: "Coding" },
  { id: "sentry", name: "Sentry", description: "Inspect recent Sentry issues and events", category: "Coding" },
  { id: "build-ios-apps", name: "Build iOS Apps", description: "Build, refine, and debug iOS apps with App Intents, SwiftUI, and Xcode workflows", category: "Coding" },
  { id: "build-macos-apps", name: "Build macOS Apps", description: "Build, debug, instrument, and implement macOS apps with SwiftUI and AppKit guidance", category: "Coding" },
  { id: "build-web-apps", name: "Build Web Apps", description: "Build frontend-focused web apps with generated assets, browser testing, payments, and databases", category: "Coding" },
  { id: "chatgpt-apps", name: "ChatGPT Apps", description: "Build ChatGPT Apps and prepare submission materials.", category: "Coding" },
  { id: "test-android-apps", name: "Test Android Apps", description: "Reproduce issues, inspect UI, and capture performance evidence from Android emulators", category: "Coding" },
  { id: "expo", name: "Expo", description: "Build, deploy, upgrade, and debug Expo and React Native apps", category: "Coding" },
  { id: "coderabbit", name: "CodeRabbit", description: "Run AI-powered code review for your current changes", category: "Coding" },
  { id: "neon-postgres", name: "Neon Postgres", description: "Manage Neon Serverless Postgres projects and databases", category: "Coding" },
  { id: "plugin-eval", name: "Plugin Eval", description: "Start from chat, then evaluate or benchmark locally", category: "Coding" },
  { id: "cloudinary", name: "Cloudinary", description: "Manage, search, and transform your Cloudinary media library directly from Codex.", category: "Coding" },
  { id: "hostinger", name: "Hostinger", description: "Hostinger Horizons lets you build real websites and apps just by describing what you want.", category: "Coding" },
  { id: "marcopolo", name: "MarcoPolo", description: "MarcoPolo spins up a secure container where Codex can work with your actual data.", category: "Coding" },
  { id: "quicknode", name: "Quicknode", description: "Manage your Quicknode infrastructure directly in OpenAI.", category: "Coding" },
  { id: "sendgrid", name: "SendGrid", description: "Connector for interacting with the SendGrid email API.", category: "Coding" },
  { id: "statsig", name: "Statsig", description: "Bring your Statsig workspace into Codex.", category: "Coding" },
  { id: "vantage", name: "Vantage", description: "Cloud observability and optimization for infrastructure costs.", category: "Coding" },
  { id: "yepcode", name: "YepCode", description: "Build custom AI tools using your own code with schema-defined inputs.", category: "Coding" },
  { id: "render", name: "Render", description: "Deploy, debug, monitor, and migrate apps on Render.", category: "Coding" },
  { id: "temporal", name: "Temporal", description: "Develop, run, and manage Temporal applications across the platform lifecycle", category: "Coding" },
  { id: "supabase", name: "Supabase", description: "Supabase skills and MCP tools for Codex", category: "Coding" },
  { id: "codex-security", name: "Codex Security", description: "Security scanning for your codebase", category: "Coding" },
  { id: "canva", name: "Canva", description: "Search, create, and edit designs", category: "Design" },
  { id: "figma", name: "Figma", description: "Design-to-code workflows powered by the Figma integration", category: "Design" },
  { id: "remotion", name: "Remotion", description: "Create motion graphics from prompts", category: "Design" },
  { id: "biorender", name: "BioRender", description: "Create professional scientific figures in minutes.", category: "Design" },
  { id: "hyperframes", name: "HyperFrames by HeyGen", description: "Write HTML and render video", category: "Design" },
  { id: "cogedim", name: "Cogedim", description: "One of France's leading real estate developers.", category: "Lifestyle" },
  { id: "finn", name: "FINN", description: "Flexible car subscription mobility without long-term commitments.", category: "Lifestyle" },
  { id: "myregistry", name: "MyRegistry.com", description: "Gift registry workflow for the gifts you really want.", category: "Lifestyle" },
  { id: "setu-bharat-connect-billpay", name: "Setu Bharat Connect BillPay", description: "Pay utility bills through simple conversation.", category: "Lifestyle" },
  { id: "weatherpromise", name: "WeatherPromise", description: "Protect your trip and get reimbursed if it rains more than promised.", category: "Lifestyle" },
  { id: "linear", name: "Linear", description: "Find and reference issues and projects.", category: "Productivity" },
  { id: "atlassian-rovo", name: "Atlassian Rovo", description: "Manage Jira and Confluence fast", category: "Productivity" },
  { id: "google-calendar", name: "Google Calendar", description: "Manage Google Calendar events and schedules", category: "Productivity" },
  { id: "gmail", name: "Gmail", description: "Read and manage Gmail", category: "Productivity" },
  { id: "slack", name: "Slack", description: "Read and manage Slack", category: "Productivity" },
  { id: "teams", name: "Teams", description: "Summarize Teams and draft follow-ups", category: "Productivity" },
  { id: "sharepoint", name: "SharePoint", description: "Summarize SharePoint sites and files", category: "Productivity" },
  { id: "outlook-email", name: "Outlook Email", description: "Triage Outlook inboxes and draft replies", category: "Productivity" },
  { id: "outlook-calendar", name: "Outlook Calendar", description: "Manage Outlook schedules and meeting changes", category: "Productivity" },
  { id: "jam", name: "Jam", description: "Screen record with context", category: "Productivity" },
  { id: "stripe", name: "Stripe", description: "Payments and business tools", category: "Productivity" },
  { id: "box", name: "Box", description: "Search and reference your documents", category: "Productivity" },
  { id: "google-drive", name: "Google Drive", description: "Work across Drive, Docs, Sheets, and Slides", category: "Productivity" },
  { id: "notion", name: "Notion", description: "Notion workflows for specs, research, meetings, and knowledge capture", category: "Productivity" },
  { id: "amplitude", name: "Amplitude", description: "Product analytics and funnels", category: "Productivity" },
  { id: "attio", name: "Attio", description: "Connect Codex directly to your CRM workspace.", category: "Productivity" },
  { id: "brand24", name: "Brand24", description: "Explore brand mentions, sentiment, and media signals.", category: "Productivity" },
  { id: "brex", name: "Brex", description: "Review company finances through natural conversation.", category: "Productivity" },
  { id: "carta-crm", name: "Carta CRM", description: "Keep deals, companies, and relationships in view.", category: "Productivity" },
  { id: "channel99", name: "Channel99", description: "Real-time go-to-market intelligence.", category: "Productivity" },
  { id: "circleback", name: "Circleback", description: "AI-powered meeting notes, action items, and follow-ups.", category: "Productivity" },
  { id: "clickup", name: "ClickUp", description: "Turn Codex into your ClickUp command center.", category: "Productivity" },
  { id: "common-room", name: "Common Room", description: "Embed complete buyer intelligence directly within Codex.", category: "Productivity" },
  { id: "conductor", name: "Conductor", description: "Retrieve proprietary brand visibility and search metrics.", category: "Productivity" },
  { id: "coupler", name: "Coupler.io", description: "Analyze cross-channel marketing, financial, sales, and ecommerce data.", category: "Productivity" },
  { id: "coveo", name: "Coveo", description: "Search your enterprise content", category: "Productivity" },
  { id: "demandbase", name: "Demandbase", description: "Rich B2B data and GTM analysis.", category: "Productivity" },
  { id: "docket", name: "Docket", description: "Turn sales knowledge into instant answers.", category: "Productivity" },
  { id: "domotz", name: "Domotz", description: "Monitor and manage network infrastructure.", category: "Productivity" },
  { id: "dovetail", name: "Dovetail", description: "Turn customer feedback into decisions.", category: "Productivity" },
  { id: "egnyte", name: "Egnyte", description: "Work with documents and files stored in Egnyte.", category: "Productivity" },
  { id: "fireflies", name: "Fireflies", description: "Bring meetings and knowledge directly into Codex.", category: "Productivity" },
  { id: "fyxer", name: "Fyxer", description: "Write emails that sound like you.", category: "Productivity" },
  { id: "granola", name: "Granola", description: "Pull real context from past conversations.", category: "Productivity" },
  { id: "happenstance", name: "Happenstance", description: "Search your professional network with natural language.", category: "Productivity" },
  { id: "help-scout", name: "Help Scout", description: "Sync mailboxes and conversations for support workflows.", category: "Productivity" },
  { id: "highlevel", name: "HighLevel", description: "Unified CRM, automation, and client communication platform.", category: "Productivity" },
  { id: "hubspot", name: "HubSpot", description: "Analyze patterns, create records, and manage CRM operations.", category: "Productivity" },
  { id: "keybid-puls", name: "KeyBid Puls", description: "ROI calculator for short-term rental investments.", category: "Productivity" },
  { id: "mem", name: "Mem", description: "Give Codex the full context of your second brain.", category: "Productivity" },
  { id: "monday", name: "Monday.com", description: "Interact with monday.com through a powerful MCP connector.", category: "Productivity" },
  { id: "motherduck", name: "MotherDuck", description: "Connect assistants to your MotherDuck data warehouse.", category: "Productivity" },
  { id: "network-solutions", name: "Network Solutions", description: "Search for an available domain quickly.", category: "Productivity" },
  { id: "omni-analytics", name: "Omni Analytics", description: "Query Omni using your team's semantic model.", category: "Productivity" },
  { id: "otter", name: "Otter.ai", description: "Search and retrieve meeting intelligence and transcripts.", category: "Productivity" },
  { id: "pipedrive", name: "Pipedrive", description: "Sync Pipedrive deals and contacts for use in Codex.", category: "Productivity" },
  { id: "pylon", name: "Pylon", description: "Access customer support workflows directly from Codex.", category: "Productivity" },
  { id: "ranked-ai", name: "Ranked AI", description: "Industry-leading AI SEO and PPC software.", category: "Productivity" },
  { id: "razorpay", name: "Razorpay", description: "Access payment data through conversation.", category: "Productivity" },
  { id: "read-ai", name: "Read AI", description: "Bring meeting intelligence directly into AI workflows.", category: "Productivity" },
  { id: "responsive", name: "Responsive", description: "Work with your organization's data inside Codex.", category: "Productivity" },
  { id: "semrush", name: "Semrush", description: "Structured SEO and traffic data for domains and keywords.", category: "Productivity" },
  { id: "signnow", name: "SignNow", description: "Get documents signed faster.", category: "Productivity" },
  { id: "skywatch", name: "SkyWatch", description: "Search satellite imagery from top providers.", category: "Productivity" },
  { id: "streak", name: "Streak", description: "CRM built directly into Gmail.", category: "Productivity" },
  { id: "teamwork", name: "Teamwork.com", description: "Sync Teamwork projects and tasks.", category: "Productivity" },
  { id: "united-rentals", name: "United Rentals", description: "Get the right equipment for the job.", category: "Productivity" },
  { id: "waldo", name: "Waldo", description: "AI-powered strategy platform for agencies and brands.", category: "Productivity" },
  { id: "windsor-ai", name: "Windsor.ai", description: "Connect marketing and business data sources to Codex.", category: "Productivity" },
  { id: "life-science-research", name: "Life Science Research", description: "General life-sciences research with evidence synthesis.", category: "Research" },
  { id: "zotero", name: "Zotero", description: "Find papers and add citations from Zotero", category: "Research" },
  { id: "alpaca", name: "Alpaca", description: "Stop watching the markets.", category: "Research" },
  { id: "binance", name: "Binance", description: "Access and explore public market data using natural language.", category: "Research" },
  { id: "cb-insights", name: "CB Insights", description: "Private markets research agent workflows.", category: "Research" },
  { id: "cube", name: "Cube", description: "Query live Cube actuals, budgets, and forecasts.", category: "Research" },
  { id: "daloopa", name: "Daloopa", description: "High-quality fundamental data from SEC filings and investor materials.", category: "Research" },
  { id: "dow-jones-factiva", name: "Dow Jones Factiva", description: "Search the Factiva global news archive.", category: "Research" },
  { id: "govtribe", name: "GovTribe", description: "Search government contracts, awards, and vendors.", category: "Research" },
  { id: "moodys", name: "Moody's", description: "Credit and risk intelligence", category: "Research" },
  { id: "morningstar", name: "Morningstar", description: "Investment and fund research", category: "Research" },
  { id: "mt-newswires", name: "MT Newswires", description: "Real-time global financial news directly in Codex.", category: "Research" },
  { id: "particl", name: "Particl Market Research", description: "Answer ecommerce research questions directly in Codex.", category: "Research" },
  { id: "pitchbook", name: "PitchBook", description: "Structured private capital market data.", category: "Research" },
  { id: "policynote", name: "PolicyNote", description: "Structured policy and regulatory intelligence.", category: "Research" },
  { id: "quartr", name: "Quartr", description: "Access structured first-party IR data from public companies.", category: "Research" },
  { id: "readwise", name: "Readwise", description: "The official app for Readwise and Reader.", category: "Research" },
  { id: "scite", name: "Scite", description: "Answers grounded in peer-reviewed research you can verify.", category: "Research" },
  { id: "taxdown", name: "Taxdown", description: "Tax guidance for Spain for individuals and autónomos.", category: "Research" },
  { id: "third-bridge", name: "Third Bridge", description: "Critical context and trusted expert insights.", category: "Research" },
  { id: "tinman-ai", name: "Tinman AI", description: "Help loan officers and underwriters model financing scenarios quickly.", category: "Research" }
];

export const DEFAULT_MCP_SERVER_CATALOG: McpServerCatalogEntry[] = [
  { id: "leeway-agent-registry", name: "leeway-agent-registry", description: "Registry and routing context for Agent Lee specialist systems." },
  { id: "leeway-desktop-commander", name: "leeway-desktop-commander", description: "Desktop command and automation bridge." },
  { id: "leeway-docs-rag", name: "leeway-docs-rag", description: "Document retrieval and grounded answer support." },
  { id: "leeway-health", name: "leeway-health", description: "Runtime health and status monitoring." },
  { id: "leeway-insforge", name: "leeway-insforge", description: "Insforge workflow server for deeper repo operations." },
  { id: "leeway-memory", name: "leeway-memory", description: "Memory, session context, and recall support." },
  { id: "leeway-planner", name: "leeway-planner", description: "Planning and task graph orchestration." },
  { id: "leeway-playwright", name: "leeway-playwright", description: "Browser automation, inspection, and evidence capture." },
  { id: "leeway-scheduling", name: "leeway-scheduling", description: "Scheduling and workflow timing support." },
  { id: "leeway-testsprite", name: "leeway-testsprite", description: "Testing and validation execution support." },
  { id: "leeway-validation", name: "leeway-validation", description: "Policy, verification, and final validation checks." }
];

export const DEFAULT_AGENT_CATALOG: AgentCatalogEntry[] = [
  { id: "agent-lee-prime", name: "Agent Lee Prime", description: "Primary chat, planning, and execution lead for the sidebar and VS Code chat." },
  { id: "leeway-agent-registry", name: "Agent Registry", description: "Resolves specialist systems, routing context, and sovereign capability lookup." },
  { id: "frontend-mcp", name: "Frontend MCP", description: "Front-end build, UI implementation, and browser-facing repair workflows." },
  { id: "backend-mcp", name: "Backend MCP", description: "Back-end implementation, APIs, and service-side code paths." },
  { id: "design-system-mcp", name: "Design System MCP", description: "Design system alignment, component consistency, and UI tokens." },
  { id: "creative-mcp", name: "Creative MCP", description: "Creative generation, branded layout support, and visual ideation." },
  { id: "memory-mcp", name: "Memory MCP", description: "Memory persistence, recall, and context stitching for longer workflows." },
  { id: "scheduler-mcp", name: "Scheduler MCP", description: "Queued execution timing, staged follow-ups, and task sequencing." },
  { id: "fs-nav-agent", name: "FS Nav Agent", description: "File system navigation and repo traversal support." },
  { id: "host-exec-agent", name: "Host Exec Agent", description: "Host-side execution and system-bridge operations." },
  { id: "ui-builder-mcp", name: "UI Builder MCP", description: "UI assembly, structure generation, and component build support." },
  { id: "media-forge-agent", name: "Media Forge Agent", description: "Image, media, and asset-generation workflows." },
  { id: "leeway-build-auditor-mcp", name: "Build Auditor MCP", description: "Build validation, diagnostics, and evidence-oriented auditing." }
];
